---
title: 异常
date: 2019-08-29 23:12:28
categories: Java
---

> JAVA异常

<!-- more -->

### 1. 分类

Throwable 类是 JAVA 中所有错误或者异常的超类

- 只有当对象是 此类或者子类之一 的实例时，才能通过 JAVA 虚拟机或者 throw 语句进行抛出

### 2. 继承体系

- Throwable

  - Error

  > 严重错误，一般不便携针对性的代码

  - Exception

  > 非严重错误，可以添加处理方法进行处理

### 3. JVM的默认异常处理 

- main 方法接受到异常

  处理方式:

  - 自己处理(try-catch)，然后继续运行
  - 如果不处理，交给 main 的 jvm进行处理
```
  JVM 默认的异常处理机制: 处理异常，并打印异常的信息，并停止程序的运行
```


### 4. 使用

#### 4.1 函数声明异常

throws Exception  标明该方法可能会产生异常，如果需要使用该方法，就需要处理该异常，或者继续进行抛出

```java
// 单个异常
public void test() throws Exception {
}
// 多个异常
public void test() throws Exception1, Exception2 {
}
```

- 抛出异常时，最好声明具体的异常类型 （方便外部 针对性进行处理)

#### 4.2 处理

- 对于异常的捕获 使用 try  catch
- try 可以匹配 多个 catch, 每个catch对于一种异常

```java
try {
	int x = 4/0;
} catch (Exception e)
{
	System.out.println(e.getMessage());
}finally {
	System.out.println("最终肯定执行");
}
```

- 注意：
  - 如果 多个 catch块中异常有继承关系，父类异常 catch 块 放在最下面

### 4.3 自定义异常

- 自定义的异常 继承 Exception类即可 

> 如果是严重错误，停止程序运行，则可以继承  RuntimeException 或其子类

```java
public class Collection1 {
    public static void main(String[] args) {
        Demo d = new Demo();
        try {
            int c = d.div(4, -1);
        } catch (FushuException e)
        {
            System.out.println(e.getMessage());
        }finally {
            System.out.println("最终肯定执行");
        }
    }

    public void test() throws Exception {
    }
}

class FushuException extends Exception {
    /* Exception 有 String 参数的构造函数，其调用了父类的方法
    *  因此 此处可以直接调用 父类的方法
    *  而不需要自己 重写 getMessage方法
    * */
    FushuException(String msg)
    {
        super(msg);
    }
}

class Demo {
    /* 方法需要抛出异常*/
    public int div(int a, int b) throws FushuException {
        if (b < 0) {
            throw new FushuException("不可为负数");
        }
        return a/b;
    }
}
```

### 4.4 throws 与 throw区别

- throws 用于 函数上， throw 用于函数内部
- throws 可以跟多个异常类，用逗号隔开； throw 跟的是异常对象

### 4.5 RuntimeException

- 一个非常特殊的异常

> 如果在函数内抛出该异常（或该异常子类), 函数上可以不用声明， 编译可以通过
>
> 如果 函数上声明了该异常， 调用者可以不用处理，编译可以通过

- 该异常作用:

> 该异常发生，表示发生了验证错误，希望程序进行停止，所以不需要也不想要该异常被处理
>
> 需要对代码进行修正，而非简单的 try catch

### 4.6 finally

- finally 部分的内容肯定会被执行
- try finally 可以进行搭配，不适用 catch

> 仅仅 使用 try finally，表示 不对异常进行处理（抛出），但是有必须要执行的代码(所以放在 finally中)

```java
try{

}finally{
}
```

### 4.7 子父类异常

- 子类的异常，需要小于 父类的异常

> 子类在覆盖父类的方法时，如果父类的方法抛出了异常，那么子类只能抛出 父类的抛出的异常，或者该异常的子类 

> 如果 父类方法抛出 多个异常， 那么子类在覆盖方法时，只能抛出父类异常的子集

> 如果 父类方法没有抛出异常，  那么子类覆盖方法时，也不可以抛出 异常!!!!!!